language: r
r:
  - bioc-devel
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpoppler-cpp-dev libmagick++-dev
# for codecov
r_packages:
  - covr
  - magick
cache:
  packages: true
notifications:
  email:
    recipients:
      - felix.gm.ernst-travis@outlook.com
    on_success: change
    on_failure: always
